### PR TITLE
PYTHON-3620 Ensure unittest-xml-reporting is Installed in Evergreen Tasks

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Review by ShaneHarvey — COMMENTED** [review]
IIUC this will install unittest-xml-reporting even when testing with a system python. Are we okay with that? We usually try not to install packages onto the system as not to mess with other Evergreen tasks.

**Comment by blink1073** [comment]
Should we always create a virtualenv then?

**Comment by ShaneHarvey** [comment]
I think always using a venv would be a great idea but I suspect it will come with some challenges and end up being more work. How about for now we only install unittest-xml-reporting in places where we already create a virtualenv? Then we can open and backlog a ticket to always use venvs.

**Comment by blink1073** [comment]
Done, and https://jira.mongodb.org/browse/PYTHON-3625

**Review by ShaneHarvey — APPROVED** [review]

**Pull request merged**
