### PR TITLE
PYTHON-4574 - FaaS detection logic mistakenly identifies EKS as AWS Lambda

### PR DESCRIPTION
**Pull request by NoahStapp**

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
What about cases where a container is deployed on AWS Lambda? https://docs.aws.amazon.com/lambda/latest/dg/images-create.html

**Comment by NoahStapp** [comment]
> What about cases where a container is deployed on AWS Lambda? [docs.aws.amazon.com/lambda/latest/dg/images-create.html](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html)

If the correct environment variables are present for both AWS Lambda and a container,  we'd need to decide what the correct result is.

**Comment by ShaneHarvey** [comment]
Let's move this convo to the drivers ticket/PR.

**Review by blink1073 — APPROVED** [review]
LGTM!

**Review by caseyclements — APPROVED** [review]
LGTM

**Pull request merged**
