### PR TITLE
PYTHON-4505 Set up EVG uploads for v4.8 branch

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
evergreen retry

**Comment by ShaneHarvey** [comment]
The coverage report is still failing:
```
 [2024/06/24 10:26:04.875] Command 'shell.exec' in function 'download and merge coverage' (step 1.2 of 1) failed: shell script encountered problem: exit code 1.
 [2024/06/24 10:26:04.875] Finished command 'shell.exec' in function 'download and merge coverage' (step 1.2 of 1) in 13.40796604s.
 [2024/06/24 10:26:04.875] Running task commands failed: running command: command failed: shell script encountered problem: exit code 1
 [2024/06/24 10:26:04.875] Finished running task commands in 13.428290325s.
 [2024/06/24 10:26:04.944] Task completed - FAILURE.
```

Also I see this warning:
```
 [2024/06/24 10:26:05.080] Performing S3 put to file 'Coverage Report/a7b6938ce877756b4e3dbaac3e3a86b867e12aba/6679a0e6f6df76000720b9c7/mongo_python_driver_v4.8_Coverage_Report_patch_a7b6938ce877756b4e3dbaac3e3a86b867e12aba_6679a0e6f6df76000720b9c7_24_06_24_16_37_59/logs/mongo_python_driver_v4.8_Coverage_Report_coverage_report_patch_a7b6938ce877756b4e3dbaac3e3a86b867e12aba_6679a0e6f6df76000720b9c7_24_06_24_16_37_59-0-mongodb-logs.tar.gz' in bucket 'mongo-python-driver-v4.8' (attempt 1 of 5).
 [2024/06/24 10:26:05.349] Bucket names containing dots that are created after Sept. 30, 2020 are not guaranteed to have valid attached URLs.
```

Is the dots in the bucket name a problem we need to workaround?

**Comment by blink1073** [comment]
I'm debugging the coverage issue.  For the bucket name, we're fine to ignore that warning:

"For best compatibility, we recommend that you avoid using dots (.) in bucket names, except for buckets that are used only for static website hosting. If you include dots in a bucket's name, you can't use virtual-host-style addressing over HTTPS, unless you perform your own certificate validation. This is because the security certificates used for virtual hosting of buckets don't work for buckets with dots in their names."

https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html

**Comment by blink1073** [comment]
We're blocked on coverage for now, we're lacking ListObjectsV2 permission.  We discussed merging for now with this known limitation.

**Review by ShaneHarvey — APPROVED** [review]

**Pull request merged**
