### PR TITLE
PYTHON-4507 pip>=21.3 is required for editable installs

### PR DESCRIPTION
**Pull request by ShaneHarvey**
https://jira.mongodb.org/browse/PYTHON-4507

### CODE REVIEW

**Comment by blink1073** [comment]
Similarly, can you please fold in the changelog notes from #1710 to this PR?

**Comment by blink1073** [comment]
Or would you rather I merge that one first?

**Comment by ShaneHarvey** [comment]
How about you merge your PR and I'll rebase?

**Comment by blink1073** [comment]
Done.

**Comment by ShaneHarvey** [comment]
I added the full 4.8 changelog here.

**Review by blink1073 — APPROVED** [review]
LGTM!

**Pull request merged**
