### PR TITLE
Use a standard version variable name (specified by PEP8)

### PR DESCRIPTION
**Pull request by ramnes**
See https://www.python.org/dev/peps/pep-0008/#version-bookkeeping

### CODE REVIEW

**Comment by behackett** [comment]
Since PyMongo has always used git for version control we've never thought to add __version__, but it is a pretty standard convention regardless of version control. I'll merge this for 3.1 and 2.9.

**Comment by ramnes** [comment]
Well, `pymongo.version` was already there actually, but not `pymongo.__version__`, which is much more standard and widely used.

Thanks!

**Comment by behackett** [comment]
Yep, we're on the same page. github's markdown rendering just made my comment less clear.

**Comment by behackett** [comment]
Merged to v2.9.

**Comment by behackett** [comment]
Also merged to master for 3.1. Thanks again for the patch.

**Pull request closed without merging**
