### PR TITLE
PYTHON-4609: [1/x] Migrate all pre and most post shell.exec to subprocess.exec

### PR DESCRIPTION
**Pull request by Jibola**
This PR focuses on primarily converting the pre/post functions with a few additional artifact and bootstrapping functions included as well.

## Functions with converted shell.exec --> subprocess.exec
- [x] "prepare resources"
- [x] "upload mo artifacts"
- [x] "bootstrap mongo orchestration"
- [x] "bootstrap data lake"
- [x] "stop mongo-orchestration"
- [x] "run aws ECS auth test"
- [x] "windows fix"
- [x] "make files executable"
- [x] "init test-results"
- [x] "install dependencies"

## Functions Remaining (to be done in more PRs)
- [ ] "run tests" -- combined both shell.exec calls
- [x] "download and merge coverage"
- [x] "run mod_wsgi tests"
- [x] "run mockupdb tests"
- [x] "run doctests"
- [x] "run enterprise auth tests"
- [x] "run atlas tests"
- [x] "run aws auth test with regular aws credentials"
- [x] "run aws auth test with assume role credentials"
- [x] "run aws auth test with aws EC2 credentials"
- [x] "run aws auth test with aws web identity credentials"
- [x] "run oidc auth test with aws credentials as environment variables"
- [x] "run aws auth test with aws credentials and session token as environment variables"
- [x] "cleanup"
- [x] "run-ocsp-test"
- [x] run-valid-ocsp-server
- [x] run-revoked-ocsp-server
- [x] run-valid-delegate-ocsp-server
- [x] run-revoked-delegate-ocsp-server
- [x] "run load-balancer"
- [x] "stop load-balancer"
- [x] "teardown_docker"
- [x] "teardown_aws"
- [x] "run perf tests"

### CODE REVIEW

**Comment by blink1073** [comment]
You have conflicts

**Comment by Jibola** [comment]
**Re-working this to use some drivers-evergreen-tools version of scripts!**

**Review by caseyclements — CHANGES_REQUESTED** [review]
Linting errors in static tests are definitely real.

Not sure about missing log files in other tests. Seem like the type of difference one might find from making a shell change like this but should be picked up in all tests. Let's look through when you're back.

**Comment by blink1073** [comment]
Superseded by #1997

**Pull request closed without merging**
