### PR TITLE
PYTHON-4372 & PYTHON-4378 Deprecate Python 3.7 and Update supported PyPy Versions to 3.9 and 3.10

### PR DESCRIPTION
**Pull request by NoahStapp**

### CODE REVIEW

**Comment by blink1073** [comment]
Other spots:

```
.github/workflows/release-python.yml:106:          python-version: '3.7'
.github/workflows/test-python.yml:56:        python-version: ["3.7", "3.11", "pypy-3.8"]
.github/workflows/test-python.yml:140:        python: ["3.7", "3.11"]
.github/workflows/test-python.yml:165:          python-version: '3.7'
.github/workflows/test-python.yml:197:            python-version: '3.7'
pyproject.toml:11:requires-python = ">=3.7"
pyproject.toml:33:    "Programming Language :: Python :: 3.7",
```

**Comment by NoahStapp** [comment]
> Other spots:
> 
> ```
> .github/workflows/release-python.yml:106:          python-version: '3.7'
> .github/workflows/test-python.yml:56:        python-version: ["3.7", "3.11", "pypy-3.8"]
> .github/workflows/test-python.yml:140:        python: ["3.7", "3.11"]
> .github/workflows/test-python.yml:165:          python-version: '3.7'
> .github/workflows/test-python.yml:197:            python-version: '3.7'
> pyproject.toml:11:requires-python = ">=3.7"
> pyproject.toml:33:    "Programming Language :: Python :: 3.7",
> ```

Good catch thanks, PyCharm search failed me.

**Comment by Jibola** [comment]
Do we also want to update language on some comments?
https://github.com/NoahStapp/mongo-python-driver/blob/65968579d565b4f02f40fc803da325c0be6e8971/.evergreen/run-tests.sh#L250-L251

```
# Run the tests with coverage if requested and coverage is installed.
# Only cover CPython. PyPy reports suspiciously low coverage.
PYTHON_IMPL=$($PYTHON -c "import platform; print(platform.python_implementation())")
if [ -n "$COVERAGE" ] && [ "$PYTHON_IMPL" = "CPython" ]; then
    # coverage 7.3 dropped support for Python 3.7, keep in sync with combine-coverage.sh.
    # coverage >=5 is needed for relative_files=true.
    python -m pip install pytest-cov "coverage>=5,<7.3"
    TEST_ARGS="$TEST_ARGS --cov"
fi
```

**Comment by NoahStapp** [comment]
> CPython 3.7.0|

Good catches, fixed. Bumped our `coverage` max version now that we no longer need to support Python 3.7.

**Review by Jibola — APPROVED** [review]
LGTM

**Pull request merged**
