### PR TITLE
PYTHON-3822 Add SRV test with uppercase hostname

### PR DESCRIPTION
**Pull request by ShaneHarvey**
Implements [PYTHON-3822](https://jira.mongodb.org/browse/PYTHON-3822).

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
Blocked on https://github.com/mongodb/specifications/pull/1473

**Comment by ShaneHarvey** [comment]
Split off [PYTHON-3170](https://jira.mongodb.org/browse/PYTHON-3170) to it's own PR here: https://github.com/mongodb/mongo-python-driver/pull/1424

**Comment by ShaneHarvey** [comment]
Spec PR was merged without changes so this is also ready to merge.

**Review by blink1073 — APPROVED** [review]
LGTM!

**Pull request merged**
