### PR TITLE
PYTHON-3649 Switch to Supported Build Hosts

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
evergreen retry

**Comment by blink1073** [comment]
evergreen retry

**Comment by blink1073** [comment]
evergreen retry

**Comment by blink1073** [comment]
Test failures are tracked in [PYTHON-3614](https://jira.mongodb.org/browse/PYTHON-3614)

**Review by ShaneHarvey — APPROVED** [review]

**Pull request merged**
