### PR TITLE
PYTHON-3909 Fix OIDC reauth for bulk write operations

### PR DESCRIPTION
**Pull request by ShaneHarvey**
https://jira.mongodb.org/browse/PYTHON-3909

### CODE REVIEW

**Comment by blink1073** [comment]
Hmm, I see `export DB_USER=`, but it is failing to use the username in the default context.

**Comment by blink1073** [comment]
I pushed a fix.

**Review by blink1073 — APPROVED** [review]

**Comment by blink1073** [comment]
Yeah, I agree we shouldn't need AUTH_MECH.  I'll need to make a PR to `drivers-evergreen-tools` to not use SCRAM-256 on the OIDC host.

**Comment by ShaneHarvey** [comment]
> Yeah, I agree we shouldn't need AUTH_MECH. I'll need to make a PR to drivers-evergreen-tools to not use SCRAM-256 on the OIDC host.

I don't think that's need. The test client should automatically use SCRAM-SHA-256 by default.

**Comment by ShaneHarvey** [comment]
Tests are passing besides some broken core doc links:
```
(api/pymongo/collection: line    1) broken    http://mongodb.com/docs/manual/core/2dsphere/ - 404 Client Error: Not Found for url: https://www.mongodb.com/docs/manual/core/2dsphere/
(api/pymongo/collection: line    1) broken    http://mongodb.com/docs/manual/core/2d/ - 404 Client Error: Not Found for url: https://www.mongodb.com/docs/manual/core/2d/
(api/pymongo/collection: line    1) broken    http://mongodb.com/docs/manual/core/index-hashed/ - 404 Client Error: Not Found for url: https://www.mongodb.com/docs/manual/core/index-hashed/
(api/pymongo/collection: line    1) broken    http://mongodb.com/docs/manual/core/index-text/ - 404 Client Error: Not Found for url: https://www.mongodb.com/docs/manual/core/index-text/
```

**Review by blink1073 — APPROVED** [review]
LGTM!

**Pull request merged**
