### PR TITLE
PYTHON-4646 Use a single dedicated environment for hatch

### PR DESCRIPTION
**Pull request by blink1073**
Bootstrap hatch from the release files on available hosts.  Once we can install Rust, we can use the Power8 bootstrap, and install manually on RHEL7 and z-Series.

### CODE REVIEW

**Review by caseyclements — APPROVED** [review]
This makes me laugh. If it's any consolation to you, this is the first python team that I've ever worked with that environment management wasn't the problem.

LGTM

**Review by Jibola — APPROVED** [review]

**Comment by blink1073** [comment]
Windows was broken, I had to fix that.

**Review by caseyclements — APPROVED** [review]
Failures seem unrelated. LGTM

**Comment by blink1073** [comment]
Closing, I have a different, simpler approach in mind.

**Pull request closed without merging**
