### PR TITLE
PYTHON-1735 Remove redundant type checks after document validation.

### PR DESCRIPTION
**Pull request by vasiliykovalev**
https://jira.mongodb.org/browse/PYTHON-1735

### CODE REVIEW

**Comment by behackett** [comment]
None of these checks are redundant. They are all special cases specific to RawBSONDocument that don't effect other types that inherit from MutableMapping.

**Comment by vasiliykovalev** [comment]
Sorry, I'm confused. When document type is not `RawBSONDocument`, function `validate_is_document_type` raise TypeError. Line below if statement, where we check again document type is not `RawBSONDocument`.

**Comment by vasiliykovalev** [comment]
I figured out and realized that I was wrong. Thanks for your feedback and examples. I hope I can help to project later :).

**Comment by ShaneHarvey** [comment]
Thanks!

**Comment by behackett** [comment]
No worries. Thanks for the contribution.

**Pull request closed without merging**
