### PR TITLE
PYTHON-4526 DRIVERS_TOOLS needs to be set for encryption tests

### PR DESCRIPTION
**Pull request by ShaneHarvey**
https://jira.mongodb.org/browse/PYTHON-4526

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
It's the default value if DRIVERS_TOOLS is undefined. It just makes the error message a bit clearer:
```
setup-encryption: commands[1]> bash DRIVERS_TOOLS_var_undefined/.evergreen/csfle/setup-secrets.sh
/bin/bash: DRIVERS_TOOLS_var_undefined/.evergreen/csfle/setup-secrets.sh: No such file or directory
```

vs:
```
setup-encryption: commands[1]> bash /.evergreen/csfle/setup-secrets.sh
/bin/bash: /.evergreen/csfle/setup-secrets.sh: No such file or directory
```

**Comment by caseyclements** [comment]
@ShaneHarvey Am I good to approve with the failing Windows test?

**Comment by blink1073** [comment]
>  Am I good to approve with the failing Windows test?

Yes, that is a known intermittent failure.

**Review by caseyclements — APPROVED** [review]
LGTM.

**Pull request merged**
