### PR TITLE
Updated tools.rst to reflect some of the latest tools for using Django with MongoDB

### PR DESCRIPTION
**Pull request by nesdis**

### CODE REVIEW

**Comment by nesdis** [comment]
hello @behackett Could you please take a look at this pull request? Thank you very much!

**Comment by nesdis** [comment]
Djongo makes connecting to MongoDB from Django a breeze. It translates SQL syntax generated by Django Models to pymongo query documents.

Djongo is fully tested and used in several Django projects.

**Comment by behackett** [comment]
Merged. Thanks.

**Comment by nesdis** [comment]
@behackett When do the changes merged here reflect on https://api.mongodb.com/python/current/tools.html?

**Comment by behackett** [comment]
When we release PyMongo 3.6, which should happen today. Good timing.

**Pull request closed without merging**
