### PR TITLE
PYTHON-3745 Add support for multiphase initialization

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Review by NoahStapp — APPROVED** [review]

**Review by ShaneHarvey — CHANGES_REQUESTED** [review]
Should we set https://docs.python.org/3/c-api/module.html#c.Py_MOD_MULTIPLE_INTERPRETERS_SUPPORTED on 3.12+? IIUC that's what we support. The new work would be to set Py_MOD_PER_INTERPRETER_GIL_SUPPORTED.

**Comment by blink1073** [comment]
> Without Py_MOD_MULTIPLE_INTERPRETERS_SUPPORTED I think this change could break some users.

Fixed

**Comment by blink1073** [comment]
mod_wsgi 4.x Python 3.7 Ubuntu 22.04 is failing intermittently, both with and without the Py_MOD_MULTIPLE_INTERPRETERS_SUPPORTED block.   `mod_wsgi` is a bit of a black box, should we skip that particular configuration and wait until we can more directly test multiple interpreters?

**Comment by ShaneHarvey** [comment]
> mod_wsgi 4.x Python 3.7 Ubuntu 22.04 is failing intermittently

Is it also failing on main or only after the multiphase changes?

**Comment by blink1073** [comment]
After the multiphase changes

**Comment by ShaneHarvey** [comment]
I suggest we open a mod_wsgi issue to ask if multiphase init modules are supported: https://github.com/GrahamDumpleton/mod_wsgi

**Comment by blink1073** [comment]
It's the interpreter itself that defines compat as I understand it, the feature should be usable from Python 3.5.  I propose we close this issue and re-open when we can test directly against subinterpreters to see if there is an actual bug.

**Comment by ShaneHarvey** [comment]
I think it could be a bug in mod_wsgi because it has custom code to create subinterpreters. We'll also still need to keep the mod_wsgi tests even once we can test subinterpreters directly so I think we should try investigating the mod_wsgi bug now to avoid delaying this change.

**Comment by blink1073** [comment]
I'm going to have to backlog this for now until I finish OIDC work.

**Comment by ShaneHarvey** [comment]
Closing in favor of https://github.com/mongodb/mongo-python-driver/pull/1499

**Pull request closed without merging**
