### PR TITLE
PYTHON-4565 - Use pytest markers for test suite configuration

### PR DESCRIPTION
**Pull request by NoahStapp**

### CODE REVIEW

**Comment by NoahStapp** [comment]
I can't reproduce the typechecking failures locally, could it be a toolchain issue?

**Comment by blink1073** [comment]
PyOpenSSL just had a release you might be using an older version locally.

**Comment by NoahStapp** [comment]
> PyOpenSSL just had a release, you might be using an older version locally.

Just updated to the newest version, still no issue locally.

**Comment by blink1073** [comment]
It isn't the toolchain, because it is happening on GitHub.

**Comment by blink1073** [comment]
Note it also occurs in #1742

**Comment by blink1073** [comment]
Ah, they just recently added type hints to the library itself, I assume we were using types-pyopenssl before.  Can you open a ticket?

https://github.com/pyca/pyopenssl/blob/main/src/OpenSSL/py.typed

**Comment by NoahStapp** [comment]
> Ah, they just recently added type hints to the library itself, I assume we were using types-pyopenssl before. Can you open a ticket?
> 
> [pyca/pyopenssl@`main`/src/OpenSSL/py.typed](https://github.com/pyca/pyopenssl/blob/main/src/OpenSSL/py.typed?rgh-link-date=2024-07-23T19%3A04%3A44Z)

Did we explicitly include `types-pyopenssl` anywhere? I don't see any references.

**Comment by blink1073** [comment]
> Did we explicitly include types-pyopenssl anywhere? I don't see any references.

It gets pulled in by `--install-types` if there is no `py.typed` in the package.

**Review by blink1073 — APPROVED** [review]
LGTM!

**Pull request merged**
