### PR TITLE
PYTHON-2602 Test that pool paused errors are retryable

### PR DESCRIPTION
**Pull request by ShaneHarvey**
Implements:
- https://github.com/mongodb/specifications/blob/master/source/retryable-writes/tests/README.rst#prose-tests
- https://github.com/mongodb/specifications/blob/master/source/retryable-reads/tests/README.rst#poolclearederror-retryability-test

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
I'll need to investigate the test failure:
```
 [2021/07/28 00:26:42.828] FAIL [1.021s]: test_pool_paused_error_is_retryable (test_retryable_reads.TestPoolPausedError)
 [2021/07/28 00:26:42.828] ----------------------------------------------------------------------
 [2021/07/28 00:26:42.828] Traceback (most recent call last):
 [2021/07/28 00:26:42.828]   File "/data/mci/bb01e86c3119005ddeed486601d5f26a/src/test/__init__.py", line 513, in wrap
 [2021/07/28 00:26:42.828]     return f(*args, **kwargs)
 [2021/07/28 00:26:42.828]   File "/data/mci/bb01e86c3119005ddeed486601d5f26a/src/test/__init__.py", line 513, in wrap
 [2021/07/28 00:26:42.828]     return f(*args, **kwargs)
 [2021/07/28 00:26:42.828]   File "/data/mci/bb01e86c3119005ddeed486601d5f26a/src/test/test_retryable_reads.py", line 169, in test_pool_paused_error_is_retryable
 [2021/07/28 00:26:42.828]     self.assertIsInstance(cmap_events[2], ConnectionCheckOutFailedEvent)
 [2021/07/28 00:26:42.828] AssertionError: ConnectionCheckedOutEvent(('localhost', 27018), 2) is not an instance of <class 'pymongo.monitoring.ConnectionCheckOutFailedEvent'>
```
https://spruce.mongodb.com/task/mongo_python_driver_tests_python_version_amazon1_test_ssl__platform~awslinux_auth_ssl~noauth_nossl_python_version~3.6_coverage~coverage_test_5.0_replica_set_patch_9833ce0a03ae4d88b5aeaa076f4881b8699c7ce0_6100a1c01e2d17019edce78c_21_07_28_00_16_01/logs?execution=0

It's probably the same issue as https://jira.mongodb.org/browse/PYTHON-2534.

**Comment by ShaneHarvey** [comment]
Rebased and updated with RUN_ON_SERVERLESS and added CMAP events to the test output to gleam more info from test failures.

**Comment by ShaneHarvey** [comment]
Aha. Figured it out. It turns out that sometimes SDAM rediscovers the server and calls pool.ready() before the waiting thread has a chance to fail its initial checkout attempt. This race is always possible in practice. I'll have to think of a way to tweak the test to avoid this problem. Perhaps increasing the minHeartbeatInterval?

These tests also fail on load balancers.

```
======================================================================
[2021/07/28 22:23:48.969] FAIL [0.067s]: test_pool_paused_error_is_retryable (test_retryable_reads.TestPoolPausedError)
[2021/07/28 22:23:48.969] ----------------------------------------------------------------------
[2021/07/28 22:23:48.969] Traceback (most recent call last):
[2021/07/28 22:23:48.969]   File "/data/mci/656edf1583ffb844ff5d93f1ced0862e/src/test/__init__.py", line 537, in wrap
[2021/07/28 22:23:48.969]     return f(*args, **kwargs)
[2021/07/28 22:23:48.969]   File "/data/mci/656edf1583ffb844ff5d93f1ced0862e/src/test/__init__.py", line 537, in wrap
[2021/07/28 22:23:48.969]     return f(*args, **kwargs)
[2021/07/28 22:23:48.969]   File "/data/mci/656edf1583ffb844ff5d93f1ced0862e/src/test/test_retryable_reads.py", line 188, in test_pool_paused_error_is_retryable
[2021/07/28 22:23:48.969]     cmap_events[2], ConnectionCheckOutFailedEvent, msg)
[2021/07/28 22:23:48.969] AssertionError: ConnectionCheckedOutEvent(('localhost', 27017), 2) is not an instance of <class 'pymongo.monitoring.ConnectionCheckOutFailedEvent'> : [PoolCreatedEvent(('localhost', 27017), {'maxPoolSize': 1}),
[2021/07/28 22:23:48.969]  PoolReadyEvent(('localhost', 27017)),
[2021/07/28 22:23:48.969]  ConnectionCheckOutStartedEvent(('localhost', 27017)),
[2021/07/28 22:23:48.969]  ConnectionCreatedEvent(('localhost', 27017), 1),
[2021/07/28 22:23:48.969]  ConnectionReadyEvent(('localhost', 27017), 1),
[2021/07/28 22:23:48.969]  ConnectionCheckedOutEvent(('localhost', 27017), 1),
[2021/07/28 22:23:48.969]  PoolClearedEvent(('localhost', 27017), None),
[2021/07/28 22:23:48.969]  ConnectionCheckedInEvent(('localhost', 27017), 1),
[2021/07/28 22:23:48.969]  ConnectionClosedEvent(('localhost', 27017), 1, 'stale'),
[2021/07/28 22:23:48.969]  PoolReadyEvent(('localhost', 27017)),
[2021/07/28 22:23:48.969]  ConnectionCheckOutStartedEvent(('localhost', 27017)),
[2021/07/28 22:23:48.969]  ConnectionCreatedEvent(('localhost', 27017), 2),
[2021/07/28 22:23:48.969]  ConnectionCheckOutStartedEvent(('localhost', 27017)),
[2021/07/28 22:23:48.969]  ConnectionReadyEvent(('localhost', 27017), 2),
[2021/07/28 22:23:48.969]  ConnectionCheckedOutEvent(('localhost', 27017), 2),
[2021/07/28 22:23:48.969]  ConnectionCheckedInEvent(('localhost', 27017), 2),
[2021/07/28 22:23:48.969]  ConnectionCheckedOutEvent(('localhost', 27017), 2),
[2021/07/28 22:23:48.969]  ConnectionCheckedInEvent(('localhost', 27017), 2)]
```

**Comment by ShaneHarvey** [comment]
I believe I've found a suitable workaround to this test failure. We essentially repeat the test until the  until the waiting thread actually encounters a PoolClearedError. The we go ahead and verify the events. I'm validating this with a larger patch build now.

**Review by behackett — APPROVED** [review]
lgtm

**Pull request merged**
