### PR TITLE
PYTHON-2870 Add support for man/text/latex/etc.. docs output

### PR DESCRIPTION
**Pull request by ShaneHarvey**
This PR adds support for building the docs in non-html output formats. For example man/latex/text are now supported. In order to do this I removed the mongodoc extension which doesn't add much value anyway. I also regenerated sphinx's doc/Makefile with sphinx-quickstart 3.5.4.

To build the docs in different formats:
```
cd doc
make man latex text html
```

### CODE REVIEW

**Comment by behackett** [comment]
I think the point of mongodoc is to generate links to dochub references, which are supposed to be stable long term. Are you sure we aren't losing something by getting rid of it?

**Comment by ShaneHarvey** [comment]
We're not loosing anything AFAICT. We're still linking to the dochub pages. The only thing mongodoc does is automatically replace this:
```
.. mongodoc:: rs
```
with this:
```
.. seealso:: The MongoDB documentation on: `rs <https://dochub.mongodb.org/core/rs>`_
```

After this change we just explicitly link to the page:
```
.. seealso:: The `MongoDB documentation on Replication <https://dochub.mongodb.org/core/rs>`_
```

**Review by behackett — APPROVED** [review]
I see. Great. LGTM.

**Comment by kloczek** [comment]
Unsing that Makefile soes not make any sense.
All what needs to be done is correctly implement setuptools<>sphinx integration
https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html

**Comment by ShaneHarvey** [comment]
setup.py build_sphinx also works as expected after these changes:
```
$ python setup.py build_sphinx -b man --build-dir build/sphinx
--
running build_sphinx
Running Sphinx v4.1.2
making output directory... done
loading intersphinx inventory from http://www.gevent.org/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 79 added, 0 changed, 0 removed
reading sources... [100%] tutorial
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... pymongo.1 { atlas installation tutorial examples/index examples/aggregation examples/authentication examples/collations examples/copydb examples/custom_type examples/bulk examples/datetimes examples/geo examples/gevent examples/gridfs examples/high_availability examples/mod_wsgi examples/server_selection examples/tailable examples/tls examples/encryption examples/uuid faq compatibility-policy api/index api/bson/index api/bson/binary api/bson/code api/bson/codec_options api/bson/dbref api/bson/decimal128 api/bson/errors api/bson/int64 api/bson/json_util api/bson/max_key api/bson/min_key api/bson/objectid api/bson/raw_bson api/bson/regex api/bson/son api/bson/timestamp api/bson/tz_util api/pymongo/index api/pymongo/bulk api/pymongo/change_stream api/pymongo/client_session api/pymongo/collation api/pymongo/collection api/pymongo/command_cursor api/pymongo/cursor api/pymongo/database api/pymongo/driver_info api/pymongo/encryption api/pymongo/encryption_options api/pymongo/errors api/pymongo/mongo_client api/pymongo/monitoring api/pymongo/operations api/pymongo/pool api/pymongo/read_concern api/pymongo/read_preferences api/pymongo/results api/pymongo/server_api api/pymongo/server_description api/pymongo/topology_description api/pymongo/uri_parser api/pymongo/write_concern api/pymongo/event_loggers api/gridfs/index api/gridfs/errors api/gridfs/grid_file tools contributors changelog python3 migrate-to-pymongo4 migrate-to-pymongo3 developer/index developer/periodic_executor } done
build succeeded.
 
The manual pages are in build/sphinx/man.
```

**Pull request merged**
