### PR TITLE
Compare IndexModel to SON from list_indexes.

### PR DESCRIPTION
**Pull request by estobbart**
When IndexModel objects are created by the user, you can check if they exist by comparing to a collections list_index method.

### CODE REVIEW

**Comment by marcus-ahle** [comment]
:+1:

**Comment by behackett** [comment]
The problem with this change is that it makes various assumptions about the structure of the index documents returned by MongoDB and the structure of those documents change from server release to server release. I think a better idea would be to open a ticket against the server requesting a stable index document format that can be passed unaltered to the createIndexes command.

**Comment by estobbart** [comment]
@behackett Thanks. My assumption was that consistency problem was wrapped by IndexModel.

**Comment by estobbart** [comment]
https://jira.mongodb.org/browse/SERVER-21882

**Pull request closed without merging**
