### PR TITLE
PYTHON-2799 Use namespace returned from initial command response for killCursors

### PR DESCRIPTION
**Pull request by prashantmital**
This will be tested by the ADL prose test being added in #665

### CODE REVIEW

**Review by ShaneHarvey — COMMENTED** [review]
Does command cursor need this change as well?

**Comment by prashantmital** [comment]
@ShaneHarvey good point. Made the change to CommandCursor as well.

**Comment by ShaneHarvey** [comment]
Since it was overlooked does that mean there is no test coverage for CommandCursors?

**Comment by prashantmital** [comment]
@ShaneHarvey done - https://github.com/ajdavis/pymongo-mockup-tests/pull/8 
I don't have the necessary permissions to request a review on that PR.

**Review by ShaneHarvey — APPROVED** [review]

**Pull request merged**
