### PR TITLE
PYTHON-4925 Fix test bugs in $$matchAsDocument and $$matchAsRoot

### PR DESCRIPTION
**Pull request by ShaneHarvey**
PYTHON-4925 Fix test bugs in $$matchAsDocument and $$matchAsRoot

Also:
- Fixes a bug where the driverConnectionId field was missing from "server heartbeat failed" log messages.
- Avoids sending "upsert": False since various client.bulkWrite spec tests assume this field is only sent when it's True. 

Implementation for https://github.com/mongodb/specifications/pull/1706

### CODE REVIEW

**Comment by blink1073** [comment]
```
FAILED test/test_discovery_and_monitoring.py::TestUnifiedLoggingStandalone::test_Successful_heartbeat - AssertionError: 'topologyId' not found in {'driverConnectionId': 1, 'serverHost': 'localhost', 'serverPort': 27017, 'awaited': False, 'message': 'Server heartbeat started'}
FAILED test/test_discovery_and_monitoring.py::TestUnifiedLoggingStandalone::test_Topology_lifecycle - AssertionError: 'topologyId' not found in {'message': 'Starting topology monitoring'}
```

**Comment by ShaneHarvey** [comment]
This should be ready for review now, I'm expecting the tests to pass.

**Comment by blink1073** [comment]
Just some type checking left:

```
pymongo/operations.py:392: error: Argument 3 to "add_replace" of "_AsyncBulk"
has incompatible type "Optional[bool]"; expected "bool"  [arg-type]
Installing missing stub packages:
/home/runner/.local/share/hatch/env/virtual/pymongo/EKb5j68n/typing/bin/python -m pip install types-Pygments types-requests
                self._upsert,
                ^~~~~~~~~~~~


Found 4 errors in 1 file (checked 140 source files)
pymongo/operations.py:392: error: Argument 3 to "add_replace" of "_Bulk" has
incompatible type "Optional[bool]"; expected "bool"  [arg-type]
                self._upsert,
                ^~~~~~~~~~~~
pymongo/operations.py:696: error: Argument 4 to "add_update" of "_AsyncBulk"
has incompatible type "Optional[bool]"; expected "bool"  [arg-type]
                self._upsert,
                ^~~~~~~~~~~~
pymongo/operations.py:696: error: Argument 4 to "add_update" of "_Bulk" has
incompatible type "Optional[bool]"; expected "bool"  [arg-type]
                self._upsert,
                ^~~~~~~~~~~~
```

**Review by blink1073 — APPROVED** [review]
LGTM!

**Pull request merged**
