### PR TITLE
PYTHON-3686 Pin mypy dependencies, don't upgrade pip

### PR DESCRIPTION
**Pull request by ShaneHarvey**

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
Wow, pinning to pip 23.0.1 fixes the errors on Python 3.7.

**Comment by ShaneHarvey** [comment]
Oh I bet if this is related to pip's build via wheel by default change. My theory is that be mistakenly don't ship the codec_options.pyi file in the wheel.

**Comment by blink1073** [comment]
Better to be explicit and add `recursive-include bson *.pyi` to `MANIFEST.in` either way.

**Comment by ShaneHarvey** [comment]
I'll try, I do see that codec_options.pyi is already included in the wheel so I don't think it's that simple.

**Comment by ShaneHarvey** [comment]
Fixed by https://github.com/mongodb/mongo-python-driver/pull/1199

**Pull request closed without merging**
