### PR TITLE
PYTHON-3930 Add docs page for network compression

### PR DESCRIPTION
**Pull request by ShaneHarvey**
https://jira.mongodb.org/browse/PYTHON-3930

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
Rendered view here: https://pymongo--1415.org.readthedocs.build/en/1415/examples/network_compression.html

**Review by blink1073 — COMMENTED** [review]
Should we also call out `zlibCompressionLevel` here?

**Comment by ShaneHarvey** [comment]
> Should we also call out zlibCompressionLevel here?

Good idea. Done.

**Comment by blink1073** [comment]
Perhaps also link out to https://www.mongodb.com/docs/manual/reference/connection-string/#compression-options?

**Comment by ShaneHarvey** [comment]
Done, also opened [DOCSP-34026](https://jira.mongodb.org/browse/DOCSP-34026) to create a stable dochub link.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Pull request merged**
