### PR TITLE
PYTHON-3296 Test with crypt_shared version of the server being tested

### PR DESCRIPTION
**Pull request by ShaneHarvey**
https://jira.mongodb.org/browse/PYTHON-3296

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
LGTM!

**Comment by ShaneHarvey** [comment]
The mongodl.py script does not accept "6.0" or "rapid" as versions so I'm going to pause this PR until that support is added.

**Comment by ShaneHarvey** [comment]
This is blocked on https://jira.mongodb.org/browse/DRIVERS-2355

**Comment by ShaneHarvey** [comment]
Closing in favor of https://github.com/mongodb/mongo-python-driver/pull/1033

**Pull request closed without merging**
