### PR TITLE
PYTHON-4588 Don't include invalid port in URI parsing error message

### PR DESCRIPTION
**Pull request by ShaneHarvey**
https://jira.mongodb.org/browse/PYTHON-4588

An invalid port could include part of the user's password so we should avoid including it in the error message.

### CODE REVIEW

**Review by blink1073 — DISMISSED** [review]
LGTM!

**Comment by ShaneHarvey** [comment]
Hmmm. This conflicts with https://jira.mongodb.org/browse/PYTHON-3251 and makes it harder for users to debug invalid ports:
```python
>>> parse_uri("mongodb://localhost:27017 ")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shane/git/mongo-python-driver/pymongo/uri_parser.py", line 575, in parse_uri
    nodes = split_hosts(hosts, default_port=default_port)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shane/git/mongo-python-driver/pymongo/uri_parser.py", line 388, in split_hosts
    nodes.append(parse_host(entity, port))
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shane/git/mongo-python-driver/pymongo/uri_parser.py", line 149, in parse_host
    raise ValueError(
ValueError: Port contains non-digit characters. Hint: username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus
```

**Comment by blink1073** [comment]
> Hmmm. This conflicts with [jira.mongodb.org/browse/PYTHON-3251](https://jira.mongodb.org/browse/PYTHON-3251) and makes it harder for users to debug invalid ports:

We could account for it by checking if `strip(port) == port`

**Comment by ShaneHarvey** [comment]
Updated to:
```python
>>> parse_uri("mongodb://localhost:27017 ")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shane/git/mongo-python-driver/pymongo/uri_parser.py", line 581, in parse_uri
    nodes = split_hosts(hosts, default_port=default_port)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shane/git/mongo-python-driver/pymongo/uri_parser.py", line 394, in split_hosts
    nodes.append(parse_host(entity, port))
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shane/git/mongo-python-driver/pymongo/uri_parser.py", line 151, in parse_host
    raise ValueError(f"Port contains whitespace character: {c!r}")
ValueError: Port contains whitespace character: ' '
```

I think it's fine to include the one whitespace character here to help users debug their invalid URI.

**Pull request merged**
