### PR TITLE
Feature/python 1301 remove deprecated cursor manager

### PR DESCRIPTION
**Pull request by kaldown**
remove all occurrences of `cursor_manager` including tests, .rst, docstrings
checked that `python setup.py test` returns success

issue: https://jira.mongodb.org/browse/PYTHON-1301

### CODE REVIEW

**Comment by behackett** [comment]
Thanks for the patch! This is very helpful. We're currently working on PyMongo 3.6 (adding support for the upcoming MongoDB 3.6). PYTHON-1301 is slated for PyMongo 4.0. PyMongo follows [sematic versioning](http://semver.org/), and this is a backward breaking change. We'll merge this when the work for PyMongo 4.0 begins.

**Comment by kaldown** [comment]
@behackett Hi there.
Thanks for so soon response.

Can you please guide me or even share a jet issue search query, with in result could return issues that are necessary and can be proceed, rather than freeze ?

And it sill be good if there would be more [info](https://jira.mongodb.org/browse/PYTHON-859?jql=project%20%3D%20PYTHON%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20id%2C%20priority%20DESC%2C%20updated%20DESC) about contributing.
For example my second commit it's actually a  `master merge`, and I was afraid that it's a bad behavior. Maybe it would be better to send a patch, or even use `git rebase`.

Thanks a lot.

**Comment by behackett** [comment]
Merges to master are fine. That's generally where we do development. [This is the list of open issues for 3.6. ](https://jira.mongodb.org/browse/PYTHON-1367?jql=project%20%3D%20PYTHON%20AND%20fixVersion%20%3D%203.6%20and%20status%20!%3D%20Closed)

**Comment by ShaneHarvey** [comment]
@kaldown, I going to close this for now. We'll reopen when we start working on PyMongo 4.0 and [PYTHON-1301](https://jira.mongodb.org/browse/PYTHON-1301) is scheduled. Thanks!

**Comment by kaldown** [comment]
Hi there.
So whats about?
A year past since, should it be forgotten, or I can restart thread?

**Comment by ShaneHarvey** [comment]
No updates. We will reopen when we start working on PyMongo 4.0 and [PYTHON-1301](https://jira.mongodb.org/browse/PYTHON-1301) is scheduled.

**Comment by kaldown** [comment]
so "open" status is not for scheduled tasks?
Which of them I can chose then?

**Comment by ShaneHarvey** [comment]
"Open" means it's something we will work on in the future but it's not planned. Tickets with the "scheduled" status is what you can look at. More specifically you can look for ["scheduled" tasks for the next version](https://jira.mongodb.org/issues/?jql=project%20%3D%20PYTHON%20AND%20status%20%3D%20Scheduled%20AND%20resolution%20%3D%20Unresolved%20AND%20fixVersion%20%3D%203.8%20AND%20assignee%20in%20(EMPTY)%20ORDER%20BY%20assignee%20ASC%2C%20priority%20DESC%2C%20updated%20DESC) (3.8).

**Pull request closed without merging**
