### PR TITLE
PYTHON-3523 Remove getNonce command usage for 6.2+

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by juliusgeo** [comment]
We don't have support for 6.2 in our test suite, so I assumed we would have to wait for that so we could see errors for any remaining usages of getNonce.

**Comment by blink1073** [comment]
Latest is [6.3](https://evergreen.mongodb.com/task_log_raw/mongo_python_driver_test_macos__platform~macos_1014_auth~auth_ssl~ssl_test_latest_replica_set_47686c8f68363645579ee0ed0f841fdd3b7362f4_22_12_20_22_29_43/0?type=T#L751).

**Comment by blink1073** [comment]
I removed those two files.

**Review by juliusgeo — APPROVED** [review]
LGTM!

**Review by ShaneHarvey — APPROVED** [review]

**Pull request merged**
