### PR TITLE
PYTHON-3142 Stop using $where in test_maxConnecting

### PR DESCRIPTION
**Pull request by ShaneHarvey**
Removing $where fixes the test failures.

### CODE REVIEW

**Comment by juliusgeo** [comment]
Is there a way to add a unittest to ensure that this test does not fail within `n` iterations? I think that would be a good addition to this PR.

**Comment by ShaneHarvey** [comment]
> ensure that this test does not fail within n iterations

I don't want to do that because it would make this test slower and more flakey.

We could "ensure the test passes at least once in n iterations" but I also don't want to do that here since that could hide legitimate server or driver bugs (such a change would have masked this server regression).

**Review by blink1073 — APPROVED** [review]
LGTM

**Review by juliusgeo — APPROVED** [review]
LGTM!

**Pull request merged**
