### PR TITLE
PYTHON-1974 Remove manylinux containers only needed for 3.4

### PR DESCRIPTION
**Pull request by ShaneHarvey**
Minor cleanup I noticed while doing the 3.11.3 release.

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
Note the task is failing due to an unrelated issue (https://jira.mongodb.org/browse/PYTHON-2541) but it's fine to merge this change as is.

**Comment by behackett** [comment]
This seems fine since it's a change for master. What about building wheels for PyMongo 3.x?

**Comment by ShaneHarvey** [comment]
Not sure I understand the question. This change can't be backported to since 3.x still supports Python 3.4.

Although the manylinux release task is failing on evergreen it didn't hold up the 3.11.3 release. Instead, I ran the manylinux build script locally on my own machine and it worked fine. It's as simple as this:
```
./.evergreen/build-manylinux.sh
```

**Comment by behackett** [comment]
Great. I guess my question was will we be able to ship wheels for PyMongo 3.x and Python 3.4 in the future. Sounds like the answer is yes.

**Review by behackett — APPROVED** [review]

**Pull request merged**
