### PR TITLE
PYTHON-1834 Use a code formatter

### PR DESCRIPTION
**Pull request by blink1073**
Ran `black --line-length 100 .`and `isort --profile black .` on the codebase.

```
black --version
black, 22.1.0 (compiled: yes)
```

### CODE REVIEW

**Review by ShaneHarvey — CHANGES_REQUESTED** [review]
Please run black/isort again now that you've manually fixed the mypy issues.

**Comment by ShaneHarvey** [comment]
Also let's use `isort --profile black .` to fix the black + isort conflicts.

**Comment by blink1073** [comment]
> Also let's use isort --profile black . to fix the black + isort conflicts.

Done, updated top level comment

**Comment by blink1073** [comment]
Note to self, use `args: [--profile=black]` in the `pre-commit` file.

**Review by ShaneHarvey — APPROVED** [review]

**Comment by ShaneHarvey** [comment]
Note the one test failure was a flake and can be ignored.

**Pull request merged**
