### PR TITLE
Fix: Respect system DNS resolver configuration

### PR DESCRIPTION
**Pull request by anryko**
When relying on system DNS resolver configuration, such as `/etc/resolv.conf` search domain string, MongoClient is failing to connect.

**Failure example**

```bash
>>> from pymongo import MongoClient
>>> rs0 = MongoClient('andrej-mongo-shard1-1:27017', replicaSet='shard1')
>>> rs0.nodes
frozenset()
>>> rs0.list_database_names()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    rs0.list_database_names()
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1906, in list_database_names
    for doc in self.list_databases(session, nameOnly=True)]
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1887, in list_databases
    res = admin._retryable_read_command(cmd, session=session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/database.py", line 749, in _retryable_read_command
    _cmd, read_preference, session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1455, in _retryable_read
    read_pref, session, address=address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1254, in _select_server
    server = topology.select_server(server_selector)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 233, in select_server
    address))
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 190, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 207, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: andrej-mongo-shard1-1:27017: [Errno 8] nodename nor servname provided, or not known
```

**With this fix**

```bash
>>> from pymongo import MongoClient
>>> rs0 = MongoClient('andrej-mongo-shard1-1:27017', replicaSet='shard1')
>>> rs0.nodes
frozenset({('andrej-mongo-shard1-2', 27017), ('andrej-mongo-shard1-1', 27017), ('andrej-mongo-shard1-3', 27017)})
```

**Example of `/etc/resolv.conf`**

```text
nameserver 1.1.1.1
search dev.example.com
```

I can use FQDN for the seed in initial MongoClient init, but this doesn't get me much farther as my cluster configs are relying on system resolver search domain as well...

```bash
>>> rs0 = MongoClient('andrej-mongo-shard1-1.dev.example.com:27017', replicaSet='shard1')
>>> rs0.nodes
frozenset()
>>> rs0.list_database_names()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    rs0.list_database_names()
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1906, in list_database_names
    for doc in self.list_databases(session, nameOnly=True)]
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1887, in list_databases
    res = admin._retryable_read_command(cmd, session=session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/database.py", line 749, in _retryable_read_command
    _cmd, read_preference, session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1455, in _retryable_read
    read_pref, session, address=address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1254, in _select_server
    server = topology.select_server(server_selector)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 233, in select_server
    address))
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 190, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 207, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: andrej-mongo-shard1-3:27017: [Errno 8] nodename nor servname provided, or not known,andrej-mongo-shard1-2:27017: [Errno 8] nodename no
r servname provided, or not known,andrej-mongo-shard1-1:27017: [Errno 8] nodename nor servname provided, or not known
```

### CODE REVIEW

**Comment by behackett** [comment]
Using resolve.conf this way feels wrong to me. I believe that file is often auto generated. I would think you would want to use /etc/hosts. Regardless, instead of creating a dependency on dnspython, why not just us [socket.getfqdn](https://docs.python.org/3/library/socket.html#socket.getfqdn)?

**Comment by anryko** [comment]
@behackett: dnspython is a requirement for DNS record seed discovery by SRV record anyway (https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/srv_resolver.py), so it's not a new dependency. If it's absent, current functionality is not affected.
The `getfqdn` function is just a wrapper over `gethostbyaddr` and doesn't add needed resolver "search" and "domain" functionality.

**Comment by p-mongo** [comment]
Hi @anryko, I happen to have a local DNS server on my machine and I believe I reproduced the configuration you are referring to.

Here are the various files involved:

<pre>
butler# cat /etc/bind/named.conf.local 
// other stuff ...
zone "mdb" { type master; file "/etc/bind/db.mdb"; };

butler# cat /etc/bind/db.mdb          
$TTL 24h

@	IN SOA ns.here. hostnaster.ns.here. (
		1 86400 300 604800 3600)

@	IN	NS	ns.here.
@	IN	A	127.0.0.1
*	IN	A	127.0.0.1

rstest	IN	A	127.0.0.1

butler# cat /etc/resolv.conf
search here mdb
nameserver 127.0.0.1
</pre>

Thus I have a `.mdb` domain with `rstest.mdb` host defined, and `mdb` added to the dns search list in resolv.conf.

With the search list, Python's getaddrinfo does resolve the bare host name:

<pre>
butler% python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getaddrinfo('rstest',80)
[(2, 1, 6, '', ('127.0.0.1', 80)), (2, 2, 17, '', ('127.0.0.1', 80)), (2, 3, 0, '', ('127.0.0.1', 80))]
</pre>

Python 3 produces different output but also resolves:

<pre>
butler% python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getaddrinfo('rstest',80)
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 80)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 80)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('127.0.0.1', 80))]
>>> socket.getaddrinfo('rstest',27017)
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 27017)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 27017)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('127.0.0.1', 27017))]
</pre>

If I remove mdb from the dns search list, resolution fails as expected:

<pre>
butler% python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getaddrinfo('rstest',80)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
</pre>

Then, I defined a replica set using bare host names as configuration, using the setup script at https://github.com/p-mongo/tests/blob/master/driver-dns-suffix/setup.rb:

<pre>
replset:SECONDARY> rs.config()
{
	"_id" : "replset",
	"version" : 3,
	"protocolVersion" : NumberLong(1),
	"members" : [
		{
			"_id" : 0,
			"host" : "rstest:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 1,
			"host" : "rstest:27018",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 2,
			"host" : "rstest:27019",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		}
	],
	"settings" : {
		"chainingAllowed" : true,
		"heartbeatIntervalMillis" : 2000,
		"heartbeatTimeoutSecs" : 10,
		"electionTimeoutMillis" : 10000,
		"catchUpTimeoutMillis" : -1,
		"catchUpTakeoverDelayMillis" : 30000,
		"getLastErrorModes" : {
			
		},
		"getLastErrorDefaults" : {
			"w" : 1,
			"wtimeout" : 0
		},
		"replicaSetId" : ObjectId("5df3d7b3f2b410e18d58dac0")
	}
}
</pre>

The Python driver appears to be able to connect to this deployment as expected:

<pre>
butler% python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymongo
>>> pymongo.version
'3.10.0'
>>> a=pymongo.MongoClient('mongodb://localhost:27017/?replicaSet=replset')
>>> a.nodes
frozenset([(u'rstest', 27019), (u'rstest', 27018), (u'rstest', 27017)])
>>> a.admin.command('ping')
{u'$clusterTime': {u'clusterTime': Timestamp(1576270540, 1), u'signature': {u'keyId': 0L, u'hash': Binary('\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 0)}}, u'ok': 1.0, u'operationTime': Timestamp(1576270540, 1)}
</pre>

So, it seems that in my test the Python driver is able to correctly resolve host names using the system specified dns search suffixes.

- What is your operating system and version, and Python version?
- What is the result of running just the `getaddrinfo` in a clean Python environment?

**Comment by anryko** [comment]
Hi @p-mongo, thank you for investigation and detailed response. The problem I encountered is relevant for MacOS (10.15.2 specifically in my case, with brew installed python 2.7.17 and 3.7.5). After reading your response I did try to reproduce in on Linux, but as you reported, it all works as expected there.

**Comment by anryko** [comment]
@p-mongo, as apparently this issue is not in mongo driver, feel free to close the issue. Sorry for your time.

**Pull request closed without merging**
