### PR TITLE
PYTHON-4613 - Fix Eventlet tests failing with Runner.run() cannot be …

### PR DESCRIPTION
**Pull request by NoahStapp**
…called from a running event loop

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
LGTM!

**Review by ShaneHarvey — CHANGES_REQUESTED** [review]
The eventlet tests are still failing to run async tests: https://spruce.mongodb.com/task/mongo_python_driver_tests_python_version_green_framework_rhel8__platform~rhel8_auth_ssl~auth_ssl_python_version~3.10_green_framework~eventlet_test_rapid_standalone_patch_b14420a9df321714a06ddae1a907a04846ebca20_66b538ac47c9db0007a185ff_24_08_08_21_29_19/tests?execution=0&sortBy=STATUS&sortDir=ASC

**Comment by NoahStapp** [comment]
> The eventlet tests are still failing to run async tests: [spruce.mongodb.com/task/mongo_python_driver_tests_python_version_green_framework_rhel8__platform~rhel8_auth_ssl~auth_ssl_python_version~3.10_green_framework~eventlet_test_rapid_standalone_patch_b14420a9df321714a06ddae1a907a04846ebca20_66b538ac47c9db0007a185ff_24_08_08_21_29_19/tests?execution=0&sortBy=STATUS&sortDir=ASC](https://spruce.mongodb.com/task/mongo_python_driver_tests_python_version_green_framework_rhel8__platform~rhel8_auth_ssl~auth_ssl_python_version~3.10_green_framework~eventlet_test_rapid_standalone_patch_b14420a9df321714a06ddae1a907a04846ebca20_66b538ac47c9db0007a185ff_24_08_08_21_29_19/tests?execution=0&sortBy=STATUS&sortDir=ASC)

Fixed with the latest commit.

**Comment by ShaneHarvey** [comment]
@NoahStapp the eventlet tests are still failing.

**Comment by NoahStapp** [comment]
> @NoahStapp the eventlet tests are still failing.

Fixed.

**Review by ShaneHarvey — APPROVED** [review]

**Pull request merged**
