### PR TITLE
PYTHON-3703 Fix typos and add codespell pre-commit hook 

### PR DESCRIPTION
**Pull request by jcfr**
https://jira.mongodb.org/browse/PYTHON-3703

### CODE REVIEW

**Comment by jcfr** [comment]
cc: @ShaneHarvey

**Review by ShaneHarvey — APPROVED** [review]
Thanks!

**Comment by ShaneHarvey** [comment]
@blink1073 any objections to merging? Running codespell doesn't add much time so I'm fine with adding it as a default pre-commit hook.

**Review by blink1073 — APPROVED** [review]
LGTM!

**Comment by jcfr** [comment]
Thanks for the :rocket: follow-up and review :pray:

**Pull request merged**
